# Generated by Django 5.1.4 on 2025-01-06 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_date_dailylogin_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress', models.IntegerField()),
                ('anxiety', models.IntegerField()),
                ('sleep', models.IntegerField()),
                ('mood', models.IntegerField()),
                ('physical', models.IntegerField()),
                ('water', models.IntegerField()),
                ('meal', models.CharField(max_length=255)),
                ('nutrition', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyLogIn',
        ),
    ]
