# Generated by Django 5.1.4 on 2025-01-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_moodtracker_delete_dailylogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtracker',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
